require: rubocop-rails

inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - '.pryrc'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
